### ISSUE TITLE
# The Master GuardDuty Account was not the first account in the list - failing

### ISSUE THREAD

**Issue by arkaprava-jana** [aws-samples/amazon-guardduty-multiaccount-scripts#1]
aws_account_dict.keys() --> dictionary does not return keys in order. Hence, script is failing. 

Performed an work around by creating a list of Acct. IDs and looping in the list in main function

Proposed a change also

**Comment by tomstickle** [comment]
Thanks for making us aware of this issue.  We updated the scripts with a fix for this issue.
