### ISSUE TITLE
New line character in windows is "\r\n", current enabler script only removes "\n" character from csv

### ISSUE THREAD

**Issue by avallecillac** [aws-samples/amazon-guardduty-multiaccount-scripts#22]
When running the script loading a csv file created in Windows with End Of File Sequence CRLF, the script will fail to verify email after creating member, member status gets EmailVerificationFailure because it sends the email with "\r" as trailing character so AWS GuardDuty is unable to verify it.
I'll be submitting a pull request with the fix

**Comment by ryanholland** [comment]
Thanks, I have approved the PR.
