### ISSUE TITLE
Frequency for updated findings

### ISSUE THREAD

**Issue by martinklie** [aws-samples/amazon-guardduty-multiaccount-scripts#37]
Can we please add/include an option to **Update CWE and S3 every 15 minutes** from the default if 6 hours?

**Comment by martinklie** [comment]
Thoughts?

**Comment by ryanholland** [comment]
I will look to add this option.  One thing to note however is that that the CWE publishing frequency for members cannot be changed and this can only be set by the Master.

**Comment by martinklie** [comment]
Thanks for the note.  Confirmed the members follow the master setting for CWE publishing frequency.
